### PR TITLE
Build fat binary for arm64 and x86_64 on MacOS in build.sbt

### PR DESCRIPTION
**Pull request by eatkins**
This PR reworks #11 so that we build a fat binary for osx that includes both arm64 and x86_64 code. It also adds the logic to the build.sbt to build the multi-arch version so that we can easily create new binaries in the future.

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]

**Comment by joan38** [comment]
Hi @eatkins and @eed3si9n, I'm trying to make mill work with Apple's arm64 and we have a dependency on this lib.
I upgraded to 1.3.0 but I'm still getting this error:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/jgoyeau/Library/Caches/JNA/temp/jna10824615888576569736.tmp: dlopen(/Users/jgoyeau/Library/Caches/JNA/temp/jna10824615888576569736.tmp, 1): no suitable image found.  Did find:
        /Users/jgoyeau/Library/Caches/JNA/temp/jna10824615888576569736.tmp: no matching architecture in universal wrapper
        /Users/jgoyeau/Library/Caches/JNA/temp/jna10824615888576569736.tmp: no matching architecture in universal wrapper
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
        at com.sun.jna.Native.<clinit>(Native.java:195)
        at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.<clinit>(UnixDomainSocketLibrary.java:129)
        at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.socket(UnixDomainSocketLibrary.java:165)
        at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:109)
        at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:87)
        at mill.main.Server.$anonfun$run$2(MillServerMain.scala:89)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at mill.main.Server$.lockBlock(MillServerMain.scala:201)
        at mill.main.Server.$anonfun$run$1(MillServerMain.scala:82)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at mill.main.Server$.tryLockBlock(MillServerMain.scala:208)
        at mill.main.Server.run(MillServerMain.scala:79)
        at mill.main.MillServerMain$.main(MillServerMain.scala:43)
        at mill.main.MillServerMain.main(MillServerMain.scala)
```

I was wondering if by any chance you had any hints? Are we supposed to change our usage of the lib to take advantage of this change?
Thanks

**Comment by eed3si9n** [comment]
I don't think there's JNA for ARM Macs.

**Comment by eatkins** [comment]
There is a JNI implementation that targets arm64 on osx but you have to change your code to optionally use it. JNI isn't supported on all platforms so you will probably have to handle the logic for platform detection yourself.
https://github.com/sbt/ipcsocket/blob/d5e67af724877eca42021b0d33fce7d60e795d19/src/main/java/org/scalasbt/ipcsocket/UnixDomainServerSocket.java#L91

**Comment by joan38** [comment]
Are you talking about the `boolean useJNI` parameter? Because are currently passing `false` all the time.
We are using this constructor:
https://github.com/sbt/ipcsocket/blob/d5e67af724877eca42021b0d33fce7d60e795d19/src/main/java/org/scalasbt/ipcsocket/UnixDomainServerSocket.java#L91-L92

**Comment by joan38** [comment]
Ah I see, you mean I need to pass JNI `true` there.
I tried and now I'm one step further hitting:
```
java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.UnixDomainSocketLibrary
```

**Comment by eatkins** [comment]
You also need to set the JNI parameter when constructing the `UnixDomainSocket` not just the `UnixDomainServerSocket`.

**Pull request merged**
