### PR TITLE
Support of macOS arm64

### PR DESCRIPTION
**Pull request by catap**
This PR introduced a support of macOS arm64, and open a door to add support another non `x86_64` platforms.

It contains two commits:
1. Switched from hardcoded `arch` to dynamic one,
2. Added precompiled interface for macOS 64. 

A `.dylib` looks like:
```
catap@Kirills-mini-m1 ipcsocket % file src/main/resources/darwin/*/*
src/main/resources/darwin/arm64/libsbtipcsocket.dylib:  Mach-O 64-bit dynamically linked shared library arm64
src/main/resources/darwin/x86_64/libsbtipcsocket.dylib: Mach-O 64-bit dynamically linked shared library x86_64
catap@Kirills-mini-m1 ipcsocket % 
```

Also it fixes https://github.com/sbt/ipcsocket/issues/10 and covers https://github.com/sbt/sbt/issues/6162

### CODE REVIEW

**Comment by eatkins** [comment]
This is great. I knew that the apple silicon was likely to cause problems for us. Thanks for building the binary.

I don't think the logic for selecting the arch works on all platforms, which is why CI failed. That should be straightforward to fix.

Were you actually able to get sbt to startup after this change on your computer? Naively I wouldn't expect this to be enough to get sbt working on apple silicon because the server uses the JNA implementation of ipcsocket by default. We could change the default to be JNI though. I'd love to get this released soon so that we could get a nightly version of sbt out that uses jni by default that you could test on your machine.

**Comment by catap** [comment]
@eatkins I made one more attempt. Honestly the first push was to see how CI is failed.

Now it should be better. Much better.

And yes, feel free to ping me as soon as you need my assisten to test night build on real machine.

**Comment by eatkins** [comment]
Would you mind pasting the command that you ran to build the binary?

**Comment by catap** [comment]
@eatkins 
```
gcc -arch arm64 -o /Users/catap/src/ipcsocket/src/main/resources/darwin/arm64/libsbtipcsocket.dylib -I/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home/include -I/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home/include/darwin -shared -O2 -Wall -Wextra /Users/catap/src/ipcsocket/jni/org_scalasbt_ipcsocket_JNIUnixDomainSocketLibraryProvider.c
```

I run `sbt -debug buildDarwin` on mac on intel, get a command and adjust it.

**Comment by eatkins** [comment]
Perfect. Thanks.

**Review by eatkins — APPROVED** [review]

**Comment by catap** [comment]
Renamed `arm64` to `aarch64` because it is the right name for the system.

**Comment by eatkins** [comment]
see https://github.com/sbt/sbt/pull/6165

**Comment by eatkins** [comment]
We may want to revert this in favor of creating a universal binary: https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary.

**Comment by catap** [comment]
@eatkins but universal binary exists only at macos :)

**Comment by eatkins** [comment]
Right, but at the moment we don't care about other platforms for JNI. We only use JNI for platforms that can't support JNA for whatever reason.

**Pull request merged**
