### PR TITLE
Add echo server example in Java + Maven

### PR DESCRIPTION
**Pull request by fmvilas**
Hey folks! This library popped up as a suggestion in [this Twitter thread](https://twitter.com/bsideup/status/1409947497716387847) and I thought it would awesome to give it a try. Since there were no examples or docs, I thought I'd contribute a basic example (mostly taken from tests).

Disclaimer: I'm not proficient with Java anymore so please bear with me. Last time I did Java, version 2 was the newest and coolest thing around and Maven wasn't invented yet 😄 Please feel free to make suggestions. I'll happily take them to improve the code.

Keep up the great work! 🙌

### CODE REVIEW

**Comment by eed3si9n** [comment]
Thanks for the contribution. I want to make sure that the examples do not bitrot over time. Any node or maven build should be exercised. Basically add a line under here:
https://github.com/sbt/ipcsocket/blob/60b00b1c94e310ca80a5e42f1780570067dcf0dc/.github/workflows/ci.yml#L105

Do you think you can move the Java source files under https://github.com/sbt/ipcsocket/tree/master/src/test/java/org/scalasbt/ipcsocket and maybe make symbolic links to examples/, so we don't duplicate the EchoServer?

**Comment by fmvilas** [comment]
> Thanks for the contribution. I want to make sure that the examples do not bitrot over time. Any node or maven build should be exercised.

Sure, I will.

> Do you think you can move the Java source files under https://github.com/sbt/ipcsocket/tree/master/src/test/java/org/scalasbt/ipcsocket and maybe make symbolic links to examples/, so we don't duplicate the EchoServer?

🤔 Do you think it's a good idea? I know they're both the same **now** but they serve completely different purposes. One is for testing and the other one is to provide an example. They can —and should IMHO— evolve in different ways over time. Also, not sure you want to couple tests with examples in any way. For new contributors, this relationship will be completely unexpected. For instance: if I change the examples code, I'd never expect tests to break.

**Comment by fmvilas** [comment]
I added simple compilation checks to the Github action. I'm not testing the Node.js part since it would be just a test that `npm install` works and therefore we'd not be testing the code but the NPM registry 😅 And the NPM versions are immutable so all good.

**Comment by eed3si9n** [comment]
> Do you think it's a good idea? I know they're both the same now but they serve completely different purposes. One is for testing and the other one is to provide an example.

Maybe I'm influenced by TDD (/ BDD) but I think of test code as specification / example usage code, so the closer documentation can match the test examples, the better. Another benefit of DRY would be that we can update it once during pull request and that would be reflected in examples immediately.
Or if we had to add more comments to be more pedagogic, I think that's an improvement to people who might read test as well.

In general though, I'd also want to qualify that this is a subjective nit, and I don't mean this to be a blocker for merge.

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
